-- =====================================================================
-- 智慧路灯 - 数据库建库脚本（PostgreSQL 版）
-- 数据库名：smart_street_light
-- 编码    ：UTF-8（PostgreSQL 默认，原生支持中文）
-- 适用    ：PostgreSQL 12+
--
-- 运行方式（两步）：
--   第一步（以超级用户 postgres 执行一次，创建数据库）：
--     psql -U postgres -c "CREATE DATABASE smart_street_light;"
--   第二步（连到该库执行本脚本，建表 + 初始化角色/权限/知识库）：
--     psql -U postgres -d smart_street_light -f smart_street_light.sql
-- =====================================================================

-- 说明：PostgreSQL 用「默认时区本地时间」存 TIMESTAMP；
--       原 MySQL 的 ON UPDATE CURRENT_TIMESTAMP 由后端显式写 updated_at 替代。
--       注意：MySQL 里的 `user` 表名在 PostgreSQL 是保留字，已改为 `users`。

-- ---------------------------------------------------------------------
-- 1. 设备表 device
--    对应功能：路灯设备管理、设备状态监控
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS device (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  device_id      VARCHAR(64)  NOT NULL,                                -- 设备唯一标识（对应板子设备ID）
  name           VARCHAR(128) NOT NULL DEFAULT '',                     -- 设备名称
  location       VARCHAR(255) NOT NULL DEFAULT '',                     -- 安装位置/路段
  online_status  SMALLINT     NOT NULL DEFAULT 0,                      -- 在线状态：0-离线 1-在线
  lamp_status    SMALLINT     NOT NULL DEFAULT 0,                      -- 灯开关状态：0-关灯 1-开灯
  last_heartbeat TIMESTAMP             DEFAULT NULL,                   -- 最后心跳时间
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 创建时间
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 更新时间
  CONSTRAINT uk_device_id UNIQUE (device_id)
);

-- ---------------------------------------------------------------------
-- 2. 光照历史数据表 luminance_data（时序表，数据量最大）
--    对应功能：实时监测、历史光照趋势折线图
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS luminance_data (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  device_id  VARCHAR(64)      NOT NULL,                            -- 设备标识
  luminance  DOUBLE PRECISION NOT NULL,                            -- 光照强度(lux)
  created_at TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP   -- 上报时间
);
-- 按设备+时间查询历史，必加索引
CREATE INDEX IF NOT EXISTS idx_luminance_device_time ON luminance_data (device_id, created_at);

-- ---------------------------------------------------------------------
-- 3. 光照阈值配置表 threshold_config
--    对应功能：阈值设置、路灯光照联动（自动开关）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS threshold_config (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  device_id      VARCHAR(64)      NOT NULL,                            -- 设备标识
  low_threshold  DOUBLE PRECISION NOT NULL DEFAULT 100.0,              -- 光照低于此值自动开灯(lux)
  high_threshold DOUBLE PRECISION NOT NULL DEFAULT 300.0,              -- 光照高于此值自动关灯(lux)
  updated_at     TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- 更新时间
  CONSTRAINT uk_threshold_device UNIQUE (device_id)                    -- 每个设备一条阈值配置
);

-- ---------------------------------------------------------------------
-- 4. 告警记录表 alarm_record
--    对应功能：设备离线告警、告警日志查看
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alarm_record (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  device_id   VARCHAR(64)  NOT NULL,                                -- 设备标识
  alarm_type  VARCHAR(32)  NOT NULL DEFAULT 'offline',              -- 告警类型：offline-离线
  message     VARCHAR(255) NOT NULL DEFAULT '',                     -- 告警内容
  status      SMALLINT     NOT NULL DEFAULT 0,                      -- 处理状态：0-未处理 1-已处理
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 告警时间
  resolved_at TIMESTAMP             DEFAULT NULL                    -- 处理时间
);
CREATE INDEX IF NOT EXISTS idx_alarm_device_time ON alarm_record (device_id, created_at);

-- ---------------------------------------------------------------------
-- 5. 控制指令记录表 command_record
--    对应功能：路灯手动控制、光照联动自动控制（结果反馈留痕）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS command_record (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  device_id    VARCHAR(64)  NOT NULL,                                -- 设备标识
  command_type VARCHAR(16)  NOT NULL,                                -- 指令类型：on-开灯 off-关灯
  source       VARCHAR(16)  NOT NULL DEFAULT 'manual',               -- 来源：manual-手动 auto-自动联动
  status       VARCHAR(16)  NOT NULL DEFAULT 'sent',                 -- 状态：sent-已下发 success-成功 failed-失败
  message      VARCHAR(255) NOT NULL DEFAULT '',                     -- 结果反馈信息
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 下发时间
  executed_at  TIMESTAMP             DEFAULT NULL                    -- 执行/反馈时间
);
CREATE INDEX IF NOT EXISTS idx_command_device_time ON command_record (device_id, created_at);

-- =====================================================================
-- 权限体系（RBAC）—— 对应《基本功能清单》中的两个角色
--   市政人员（municipal）：数据监测 / 数据可视化 / 设备控制 / 参数管理 / 离线告警
--   路灯管理员（admin）  ：路灯设备管理 / 告警日志查看 / 维护智能问答
-- 说明：以下 4 张表用于登录鉴权与功能级权限隔离
-- =====================================================================

-- ---------------------------------------------------------------------
-- 6. 角色表 role
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  role_code   VARCHAR(32)  NOT NULL,                                -- 角色编码（唯一，municipal/admin）
  role_name   VARCHAR(64)  NOT NULL,                                -- 角色名称
  description VARCHAR(255) NOT NULL DEFAULT '',                     -- 角色描述
  CONSTRAINT uk_role_code UNIQUE (role_code)
);

-- ---------------------------------------------------------------------
-- 7. 权限(功能)表 permission —— 每个功能点一条
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permission (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  perm_code   VARCHAR(64)  NOT NULL,                                -- 权限编码（唯一）
  perm_name   VARCHAR(64)  NOT NULL,                                -- 功能名称
  module      VARCHAR(32)  NOT NULL DEFAULT '',                     -- 所属功能模块
  description VARCHAR(255) NOT NULL DEFAULT '',                     -- 功能描述
  CONSTRAINT uk_perm_code UNIQUE (perm_code)
);

-- ---------------------------------------------------------------------
-- 8. 角色-权限关联表 role_permission
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_permission (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  role_id       BIGINT NOT NULL,                                      -- 角色ID -> role.id
  permission_id BIGINT NOT NULL,                                      -- 权限ID -> permission.id
  CONSTRAINT uk_role_perm UNIQUE (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id)       REFERENCES role (id)       ON DELETE CASCADE,
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- 9. 用户表 users（原 MySQL 的 user，因 user 是 PostgreSQL 保留字改名）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  username      VARCHAR(64)  NOT NULL,                                -- 登录账号
  password_hash VARCHAR(255) NOT NULL,                                -- 密码哈希（bcrypt，勿存明文）
  real_name     VARCHAR(64)  NOT NULL DEFAULT '',                     -- 姓名
  role_id       BIGINT       NOT NULL,                                -- 角色ID -> role.id
  status        SMALLINT     NOT NULL DEFAULT 1,                      -- 账号状态：0-禁用 1-启用
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 创建时间
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 更新时间
  CONSTRAINT uk_username UNIQUE (username),
  CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role (id)
);
CREATE INDEX IF NOT EXISTS idx_user_role ON users (role_id);

-- ---------------------------------------------------------------------
-- 10. 维护知识库 maintenance_knowledge
--    对应功能：维护智能问答（本地检索，按故障现象给原因+维护建议）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS maintenance_knowledge (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 主键
  keyword    VARCHAR(64)  NOT NULL,                                -- 故障现象关键词
  category   VARCHAR(32)  NOT NULL DEFAULT '',                     -- 故障分类
  cause      VARCHAR(255) NOT NULL,                                -- 可能原因
  suggestion VARCHAR(500) NOT NULL,                                -- 维护建议
  CONSTRAINT uk_keyword UNIQUE (keyword)
);

-- =====================================================================
-- 初始化数据：角色与权限配置（真实配置，勿删）
-- 说明：账号 / 设备 / 光照 / 告警 / 指令 等数据一律由后端接口实时写入，
--       建库脚本不再预置任何模拟数据。
-- =====================================================================

-- 角色
INSERT INTO role (id, role_code, role_name, description) VALUES
  (1, 'municipal', '市政人员',   '实时监测、数据可视化、设备控制、参数管理、离线告警'),
  (2, 'admin',     '路灯管理员', '路灯设备统一管理、告警日志查看、维护知识问答');

-- 权限（10 个功能点，与《基本功能清单》一一对应）
INSERT INTO permission (id, perm_code, perm_name, module, description) VALUES
  (1,  'luminance:monitor', '光照强度监测', '数据监测',   '实时展示当前光照强度数值'),
  (2,  'luminance:history', '历史光照趋势', '数据可视化', '折线图展示历史光照强度变化'),
  (3,  'control:linkage',   '路灯光照联动', '设备控制',   '光照低于阈值自动开灯、高于阈值自动关灯'),
  (4,  'control:manual',    '路灯手动控制', '设备控制',   '页面按钮手动远程开关路灯'),
  (5,  'config:threshold',  '阈值设置',     '参数管理',   '设置路灯开关的光照阈值参数'),
  (6,  'device:status',     '设备状态监控', '数据监测',   '查看路灯设备在线/离线状态'),
  (7,  'alarm:offline',     '设备离线告警', '告警管理',   '设备离线时告警通知'),
  (8,  'device:manage',     '路灯设备管理', '系统管理',   '添加、查看、解绑路灯设备'),
  (9,  'alarm:log',         '告警日志查看', '告警管理',   '查看历史告警记录列表'),
  (10, 'assistant:qa',      '维护智能问答', '智能体',     '对话获取维护建议（本地检索增强）');

-- 角色-权限映射
INSERT INTO role_permission (role_id, permission_id) VALUES
  -- 市政人员：功能 1~7
  (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7),
  -- 路灯管理员：功能 8~10
  (2, 8), (2, 9), (2, 10);

-- 维护知识库（智能问答检索用，按故障现象给原因+建议）
INSERT INTO maintenance_knowledge (keyword, category, cause, suggestion) VALUES
  ('离线',     '通信故障', '设备掉电、网络中断或网关异常',              '检查路灯供电与网络连接，确认网关在线；若持续离线需现场排查'),
  ('光照异常', '传感器故障', '光敏传感器被遮挡、老化或接线松动',        '清洁传感器表面，检查接线是否牢固；必要时校准或更换传感器'),
  ('频繁开关', '阈值配置',   '光照阈值设置不合理，导致灯在阈值附近反复开关（抖光）', '增大上下限差值（滞回区间），或开启连续多次确认防抖'),
  ('通信超时', '网络故障',   '网络信号弱或平台下发指令超时',            '检查设备信号强度与服务器连通性，重试指令，排查网关与运营商网络'),
  ('灯不亮',   '电源故障',   '供电异常、驱动或灯珠损坏',                '检查供电与驱动电源，确认 lamp_status，更换损坏灯珠或驱动板'),
  ('温度过高', '散热故障',   '散热不良或环境温度过高',                  '检查散热片与通风，必要时降低亮度或更换散热结构');

-- 重置自增序列（角色/权限使用了显式 id，需同步序列避免后续插入冲突）
SELECT setval(pg_get_serial_sequence('role', 'id'), (SELECT MAX(id) FROM role));
SELECT setval(pg_get_serial_sequence('permission', 'id'), (SELECT MAX(id) FROM permission));
